# Stack Operation on Tensors

Stacking operation is the process of combining multiple tensors along a given dimension.

You can stack tensors by rows or columns. e.g if you have two 1x4 (dim = 1) tensors
It is possible to stack it (by stacking I need a new dimension)

- by rows (dim=0) as 2x4 (tensor ndim = 2 ) - stack row by row 
- by columns (dim=1) and get 4x2 (tensor ndim = 2) - stack column by column 

By stacking I create a new tensor with the combination of the two original tensors 

In [1]:
import torch

In [ ]:
# stacking tensors 
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

print("Dim tensor 1 : ", tensor1.ndim)
print("Dim tensor 1 : ", tensor1.size())


Dim tensor 1 :  1
Dim tensor 2 :  torch.Size([3])


In [4]:
# Stacking is straight forward with stack() method 
tensor_rows = torch.stack((tensor1, tensor2), dim=0)

print("Stacked tensor shape : ", tensor_rows.shape)
print("Stacked tensor on rows : \n", tensor_rows)

tensor_cols = torch.stack((tensor1, tensor2), dim=1)

print("\nStacked tensor shape : ", tensor_cols.shape)
print("Stacked tensor on columns : \n", tensor_cols)

Stacked tensor shape :  torch.Size([2, 3])
Stacked tensor on rows : 
 tensor([[1, 2, 3],
        [4, 5, 6]])

Stacked tensor shape :  torch.Size([3, 2])
Stacked tensor on columns : 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
# A new dimension is created to encluse the tensors..
# It is possible to stack multiple tensors

tensor3 = torch.tensor([7, 8, 9])

tensor_rows3 = torch.stack((tensor1, tensor2, tensor3), dim=0)
print("Stacked tensor shape : ", tensor_rows3.shape)
print("Stacked tensor on rows : \n", tensor_rows3)
# Stacked along rows 

Stacked tensor shape :  torch.Size([3, 3])
Stacked tensor on rows : 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
# Also 2D tensors can be stacked
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

stacked2d_dim0 = torch.stack((tensor1, tensor2), dim=0)

print("Stacked tensor shape : ", stacked2d_dim0.shape)
print("Stacked tensor dimension : ", stacked2d_dim0.ndim)
print("Stacked tensor on rows : \n", stacked2d_dim0)

# when stacking two 2d tensor you get a 3d one...
# each 2d is taken as a single entity and stacked along rows 

Stacked tensor shape :  torch.Size([2, 2, 2])
Stacked tensor dimension :  3
Stacked tensor on rows : 
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
stacked2d_dim1 = torch.stack((tensor1, tensor2), dim=1)

print("Stacked tensor shape : ", stacked2d_dim1.shape)
print("Stacked tensor on rows : \n", stacked2d_dim1)

# Now it stack along the columns generating a new dimension

# When stacking 2d tensors dim=0 refer to the rows as the first dimension (taking it as it is)
# Instead for dim=1 it stacks along column taking the inner rows of the matrices and stacking along columns with a new dimension


# Since here we have 2d, we can stack along dim=2 ! 
# where dim=2 it refers to the inner elemnts of the metrix (element by element is dim2)

Stacked tensor shape :  torch.Size([2, 2, 2])
Stacked tensor on rows : 
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [ ]:
stacked2d_dim2 = torch.stack((tensor1, tensor2), dim=2)

print("Stacked tensor shape : ", stacked2d_dim2.shape)
print("Stacked tensor on rows : \n", stacked2d_dim2)

# This time it stacks taking elemnt by element inside of the matrix 
# In dim = 2, as anticipated the element inside each matrix are taken and collected 

# This argument about dimensions is recursive... It holds for 3d vectors with dim=3 and so on.. 

# [1, 2] :[] is dim = 0 while [-,-] is dim = 1
# [[1, 2]]: [[1,2]] is dim =0, while [1,2] is dim = 1, finally 1, 2 separatley is dim = 2


Stacked tensor shape :  torch.Size([2, 2, 2])
Stacked tensor on rows : 
 tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [ ]:
# Concatenation can be achieved also by cat

cat_tensordim0 = torch.cat((tensor1, tensor2), dim=0)
# While stack creates an additional dimension to have more tensors in a single one
# cat keep the same number of dimension fo the original ones..
print("Cat tensor shape : ", cat_tensordim0.shape)
print("Cat tensor on rows : \n", cat_tensordim0)

# It remain od ndim = 2 as 4x2 tensor collecting it by rows

Cat tensor shape :  torch.Size([4, 2])
Cat tensor on rows : 
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
cat_tensordim1 = torch.cat((tensor1, tensor2), dim=1)
# While stack creates an additional dimension to have more tensors in a single one
# cat keep the same number of dimension fo the original ones..
print("Cat tensor shape : ", cat_tensordim1.shape)
print("Cat tensor on cols : \n", cat_tensordim1)
# Now concatened along columns, as 2x4 new concatenated tensor 

Cat tensor shape :  torch.Size([2, 4])
Cat tensor on cols : 
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
