# Tensors Manipulation

Help to operate with tensors in a better way for efficient workflows. 

We refer to techniques/operations to alter the structure shape and content of tensors. 

e.g: 
- Reshaping 
- Slicing
- Joining multiple tensors 
- Splitting a single tensor in multiple sections 
- Transposing tensor (NxM to MxN transposition)
- Permuting Dimensions

In [1]:
import torch

## Reshaping

In [2]:
# Reshaping tensors
# We can rely on two methods: reshape, view 
# reshape and view have their own concept important to understand in depth ... 

original_tensor = torch.arange(12) # generate a tensor in range 0-11
print(original_tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [6]:
print("Original Tensor : \n", original_tensor)
# using reshape
print("Length of tensor : ", original_tensor.nelement())

# based on its length, 12 elements, I can reshape the vector
print("Dimension of tensor : ", original_tensor.ndim)

# To convert it to a matrix: 
reshaped_tensor = original_tensor.reshape(2,6) # I specify the new shape 
print("\nRehsaped Tensor : \n", reshaped_tensor)

print(" New tensor Dimension : ", reshaped_tensor.ndim)
print(" New tensor Elements : ", reshaped_tensor.nelement()) # You obviously keep the n of elements

Original Tensor : 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Length of tensor :  12
Dimension of tensor :  1

Rehsaped Tensor : 
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
 New tensor Dimension :  2
 New tensor Elements :  12


In [ ]:
# To convert it to a different shape 
reshaped_tensor = original_tensor.reshape(3,4) # I specify the new shape 
print("\nRehsaped Tensor : \n", reshaped_tensor)

print(" New tensor Dimension : ", reshaped_tensor.ndim)
print(" New tensor Elements : ", reshaped_tensor.nelement()) # You obviously keep the n of elements

# Still  keeping consistent dimension when reshaping 


Rehsaped Tensor : 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
 New tensor Dimension :  2
 New tensor Elements :  12


In [8]:
# For reshaping, view allow to do the same but internally it changes crucially the memory behavior 
# Internally view requires a contiguous memory (in the RAM all datapoint in view are on a sequence)

# If original_tensor is not stored contiguously in memory, view() return an error
flatten_tensor = original_tensor.view(-1) # -1 is used to automatic calculation of dimension, with -1 it keep one dimension 

print("\nRehsaped Tensor : \n", flatten_tensor)

print(" New tensor Dimension : ", flatten_tensor.ndim)
print(" New tensor Elements : ", flatten_tensor.nelement()) 


Rehsaped Tensor : 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
 New tensor Dimension :  1
 New tensor Elements :  12


In [16]:
## To check contiguity of original tensor: 
# stored in a sequential memory location
print("Original tensor is contiguous ? " , original_tensor.is_contiguous())

Original tensor is contiguous ?  True


## Slicing
Extract specific portions of tensors using slicing 


In [15]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Tensor : \n", tensor_a)
print("Tensor Dimension: ", tensor_a.ndim)
print("Tensor Shape: ", tensor_a.shape)


Original Tensor : 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Tensor Dimension:  2
Tensor Shape:  torch.Size([3, 3])


In [14]:
# extract first row 
print("First Row    : ", tensor_a[0])
print("First Column : ", tensor_a[:, 0])
# Same indexing behavior already explored before and used in lists...

First Row    :  tensor([1, 2, 3])
First Column :  tensor([1, 4, 7])


In [19]:
# Extract 2x2 matrix 
sub_tensor = tensor_a[1:, 1:]
print("Sliced Tensor : ", sub_tensor)
print("Dim : ", sub_tensor.shape)

Sliced Tensor :  tensor([[5, 6],
        [8, 9]])
Dim :  torch.Size([2, 2])


## Joining Tensor

In [22]:
# Two type of joining 
# 1. torch.cat() : try to merge tensors along an existing dimension 

tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Create new tensor with torch.cat() mering along existing dimension
# the order of the specified tensor to concatenate is relevant 
concat_tensor_rows = torch.cat((tensor_a, tensor_b), dim=0) # dim=0 cat aloong rows 
concat_tensor_cols = torch.cat((tensor_a, tensor_b), dim=1) # dim=1 cat aloong columns 

print("Tensor A : \n", tensor_a)
print("Tensor B : \n", tensor_b)

print("Concatenate on rows : \n", concat_tensor_rows)
print("Concatenate on columns : \n", concat_tensor_cols)

# We are not creating new dimensions, the ndim is preserved

Tensor A : 
 tensor([[1, 2],
        [3, 4]])
Tensor B : 
 tensor([[5, 6],
        [7, 8]])
Concatenate on rows : 
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concatenate on columns : 
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
# 2. stack() : creates a new dimension which increases the tensor's rank 
stack_tensor_rows = torch.stack((tensor_a, tensor_b), dim=0) # dim=0 stack aloong rows 
stack_tensor_cols = torch.stack((tensor_a, tensor_b), dim=1) # dim=1 stack aloong columns 

print("Tensor A : \n", tensor_a)
print("Tensor B : \n", tensor_b)

print("stack on rows shape: ", stack_tensor_rows.shape)
print("stack on rows : \n", stack_tensor_rows)

print("stack on cols shape: ", stack_tensor_cols.shape)
print("stack on columns : \n", stack_tensor_cols)

# It stacks the elemnt appending over rows or columns
# stacking increasing the dimension

Tensor A : 
 tensor([[1, 2],
        [3, 4]])
Tensor B : 
 tensor([[5, 6],
        [7, 8]])
stack on rows shape:  torch.Size([2, 2, 2])
stack on rows : 
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
stack on cols shape:  torch.Size([2, 2, 2])
stack on columns : 
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [25]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

torch.stack((tensor1, tensor2), dim=1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## Splitting Tensors

In [31]:
# splitting tensors into smaller chanks 
# 1. torch.chunk() : divide your tensor into equal sized chunks
# 2. torch.split() : allow uneven splitting based on size of tensor 

# chunk
original_tensor = torch.arange(12)

chunks = torch.chunk(original_tensor, 5, dim=0) # perform chunk on rows in chunk of 3

# even using 5, it find 4 elemnts since it uses only the maximum divisible in equally sized chunks 

# it return an iterable as a tuple 
print(chunks)
print(type(chunks))

# access as usual 
# print(chunks[0])

for chunk in chunks: 
    print(chunk)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
<class 'tuple'>
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [ ]:
# chunk doesn't give freedom on splitting. 
# Using split it is allowed uneven splitted (chunk is useful since automatically adapt)

# split
original_tensor = torch.arange(12)

splits = torch.split(original_tensor, 5, dim=0) # perform chunk on rows in chunk of 5 elements
# in splits, you specify the ideal number of elements per splits
# allowing for uneven splitting 

# it return an iterable as a tuple 
print(splits)
print(type(splits))

# access as usual 
# print(chunks[0])

for split in splits: 
    print(split)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))
<class 'tuple'>
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])


## Transposion and Permutation

transpose() : swap two dimension. e.g from MxN you get NxM matrix 

permute()   : rearranges all dimensions in the specified order 

In [36]:
original_tensor = torch.arange(24).reshape(12, 2) # get a 12x2 tensor 
print("Original : \n", original_tensor)
print("Original Shape : ", original_tensor.shape)

transposed_tensor = original_tensor.transpose(0,1) # specify the index to transpose, in terms of dimension, we transpose rows and columns 
print("Transposed : \n", transposed_tensor)
print("Transposed Shape : ", transposed_tensor.shape)


Original : 
 tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
Original Shape :  torch.Size([12, 2])
Transposed : 
 tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])
Transposed Shape :  torch.Size([2, 12])


In [ ]:
# Permute operation to rearrange dimesnion 
original_tensor = torch.arange(24).reshape(2, 3, 4) # get a 2x3x4 tensor 
print("Original : \n", original_tensor)
print("Original Shape : ", original_tensor.shape)

# from original tensor 2x3x4 (two tensors 3x4 (0, 1, 2)...
# how to rearrange it 4x2x3 (2, 0, 1) to replace indces order (4 tensor of dim 2x3)
permuted_tensor = original_tensor.permute(2, 0, 1) # we specify the index of permutation for new dimensions 
print("Permuted : \n", permuted_tensor)
print("Permuted Shape : ", permuted_tensor.shape)

Original : 
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Original Shape :  torch.Size([2, 3, 4])
Permuted : 
 tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
Permuted Shape :  torch.Size([4, 2, 3])


## Cloning and Detaching 

similarly to numpy copy to create a copy of an array

In [39]:
# with standard python code 
a = [1, 2, 3]
b = a # both a and b are same entity 

# mentioning b to hold address of a...
import copy
b = copy.deepcopy(a)

print(a)
print(b)

# separate copy, holding a difference reference in memory 

[1, 2, 3]
[1, 2, 3]


In [ ]:
# To clone a pytorch tensor 
original_tensor = torch.ones(3, 3, requires_grad=True) # specify to pytorch that this tensor will be used for gradient 
# grad is part of computation graph (original tensor on computation graph )

copy_tensor = original_tensor.clone() # new clone indipendent of the original one, same value but different memory allocation on RAM 
# copy part of computation graph 

detached_tensor = original_tensor.detach() # this detach the original tensor from computation graph 
# detached is no more part of computation graph, but storage will be same as the original tensor 
# remove from computatiion graph, but returned tensor share same storage with original one, not influencing copy
# doesn't influence the copy one 