# Introduction to Tensors

In [1]:
import torch

In [2]:
# Creating Tensors

# Scalar Tensor (0 dimension tensor) 0D

a = 42 # python scalar
# scalar tensor
scalar = torch.tensor(42)

print("Scalar Tensor : ",    scalar)
print("Scalar Dimension : ", scalar.ndim)
print("Scalar Shape : ",     scalar.shape) # No shape since it is scalar

Scalar Tensor :  tensor(42)
Scalar Dimension :  0
Scalar Shape :  torch.Size([])


In [3]:
# One Dimensional Tensor 1D: Vector

vector = torch.tensor([1, 2, 3]) # we pass a list to create a one dimensional vector

print("Vector Tensor : ",    vector)
print("Vector Dimension : ", vector.ndim)  # number of dimension 
print("Vector Shape : ",     vector.shape)     # single dimension with 3 elements its dimension, get its size


Vector Tensor :  tensor([1, 2, 3])
Vector Dimension :  1
Vector Shape :  torch.Size([3])


In [4]:
# Two Dimensional Tensor 2D: Matrix 

matrix = torch.tensor([[1, 2], [3, 4]]) # we pass a list of list to create a two dimensional tensor

print("Matrix Tensor : ",    matrix)
print("Matrix Dimension : ", matrix.ndim)  # number of dimension 
print("Matrix Shape : ",     matrix.shape) # single dimension with 2x2 elements its dimension, get its size

Matrix Tensor :  tensor([[1, 2],
        [3, 4]])
Matrix Dimension :  2
Matrix Shape :  torch.Size([2, 2])


In [5]:
# Three Dimensional Tensor 3D: Tensor
# Any tensor of more than 2D is a Tensor 

tensor3d = torch.tensor(  [[[1, 2], [3, 4]], # we pass a list of list of list to create a three dimensional tensor
                         [[1, 2], [3, 4]]]
                      ) 

print("Tensor : ",    tensor3d)
print("Tensor Dimension : ", tensor3d.ndim)  # number of dimension 
print("Tensor Shape : ",     tensor3d.shape) # single dimension with 2x2x2 elements its dimension, get its size

Tensor :  tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])
Tensor Dimension :  3
Tensor Shape :  torch.Size([2, 2, 2])


In [6]:
# When working with Tensors, PyTorch has additional capabilities then other python framework as numpy 
# such as running computation on GPU 

# GPU acceleration 

# First check if cuda is available 
if torch.cuda.is_available():
    gpu_tensor = vector.to('cuda') # move tensor to GPU 
    print("Tensor on GPU: ", gpu_tensor)

else:
    print("CUDA is not available on this machine")

# cuda: 0 indicate the main GPU, if multiple GPU are available more index of cuda are available

Tensor on GPU:  tensor([1, 2, 3], device='cuda:0')


In [7]:
# Check Tensor Properties

# other than ndim, shape..

print("Data type of matrix : ", matrix.dtype)
# by default using int64 (no floating point)

Data type of matrix :  torch.int64


In [8]:
matrix = torch.tensor([[1., 2.], [3, 4]]) # we pass a list of list to create a two dimensional tensor
print("Data type of matrix : ", matrix.dtype)
# change it to float32 

Data type of matrix :  torch.float32


In [9]:
# Check device
print("Device of Tensor : ", matrix.device)
print("Device of Tensor : ", gpu_tensor.device)

Device of Tensor :  cpu
Device of Tensor :  cuda:0


In [10]:
!nvidia-smi

Thu Jan 22 10:15:08 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.195.03             Driver Version: 570.195.03     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX PRO 500 Black...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P4             10W /   50W |     785MiB /   6113MiB |     10%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [11]:
# check boolean if stored on boolean
# Doesn't return specific device, but boolean check
print("Is tensor on CUDA : ", matrix.is_cuda)
print("Is tensor on CUDA : ", gpu_tensor.is_cuda)


Is tensor on CUDA :  False
Is tensor on CUDA :  True


In [12]:
# Shape internally rely on size
print("Shape : ", matrix.shape)
print("Size : ", matrix.size())

Shape :  torch.Size([2, 2])
Size :  torch.Size([2, 2])


In [13]:
# Check number of elements in a tensor 
print("Number of elements : ", matrix.numel())
# 2x2 matrix = 4 elements

Number of elements :  4


# Indexing Tensors

How to perform indexing and slicing, 
to efficently accessing, manipulating and analyzing data stored in tensors. 

Indexing and Slicing is done in the same way as for lists and numpy array, with additional flexibility for multi dimensional array

In [14]:
# Accessing elements in a tensor 
# Indexing
'''
tensor[row, column] : to access a specfic element
'''

tensor = torch.tensor([[10, 20, 30], 
                       [40, 50, 60], 
                       [70, 80, 90]])

print("Dimension of Tensor : ", tensor.ndim)
print("Shape of Tensor : ", tensor.shape)

# access single element
print("Element at (0,1) : ", tensor[0, 1])
# it return a scalare tensor value by accessing a specific element inside of a tensor

# access full first row 
print("First row : ", tensor[0])

# access full first column (slicing all rows from first column)
print("First column : ", tensor[:, 0])

Dimension of Tensor :  2
Shape of Tensor :  torch.Size([3, 3])
Element at (0,1) :  tensor(20)
First row :  tensor([10, 20, 30])
First column :  tensor([10, 40, 70])


In [15]:
# Slicing operation 
# to select specific range of values 

# when slicing it exclude the right limit
print("First two rows : \n", tensor[:2]) # take all columns by default, no need to refer to specific columns of interest 

print("First two columns : \n", tensor[:, :2]) # take all rows and slice columns

First two rows : 
 tensor([[10, 20, 30],
        [40, 50, 60]])
First two columns : 
 tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [16]:
# Get specific rows, cols slice
print("Second row,  columns 1 and 2:", tensor[1, 1:3])


Second row,  columns 1 and 2: tensor([50, 60])


In [17]:
# "Fancy indexing"
# To get value not in sequence but different values out of order in a tensor 

# get values in [0,1] and [2,2] of the tensor
'''
tensor[[rows], [columns]] : to access a specfic elements
'''
print("Values in [0,1] and [2,2] : ", tensor[[0,2],[1,2]])

Values in [0,1] and [2,2] :  tensor([20, 90])


In [18]:
# Boolean indexing, using boolean mask to access specific values 

# create a boolean mask with conditional statement 
mask = tensor > 50
print("mask such that values > 50 : \n", mask)

# access only value respecing the mask 
print("Tensor of masked values : \n", tensor[mask])

mask such that values > 50 : 
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Tensor of masked values : 
 tensor([60, 70, 80, 90])


In [19]:
# Modify values in the tensor via indexing
# instead of just accessing values, update it simply as in lists 

print("Tensor Originally: \n", tensor)

tensor[0,1] = 25

print("Tensor Modified: \n", tensor)


Tensor Originally: 
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
Tensor Modified: 
 tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [20]:
# In the same way values can be changed in batch
print("Tensor Originally: \n", tensor)

tensor[:,0] = torch.tensor([100, 200, 300]) # change the first column 

print("Tensor Modified: \n", tensor)

Tensor Originally: 
 tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])
Tensor Modified: 
 tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [21]:
# Advanced slicing with torch.index_select 
# more adavances slicing is possible 

indices = torch.tensor([0,2])
# after defining the indices to select
# dim=0 specify that the selection is based on the rows (dim=1 is columns)
selected_rows = torch.index_select(tensor, dim=0, index=indices)
print("Select rows : \n ", selected_rows)

selected_columns = torch.index_select(tensor, dim=1, index=indices)
print("Select columns : \n ", selected_columns)

Select rows : 
  tensor([[100,  25,  30],
        [300,  80,  90]])
Select columns : 
  tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [22]:
# Accessing tensors with steps in slicing  
print("step indexing, all rows with step of 2 in columns : \n", tensor[:, ::2]) 

step indexing, all rows with step of 2 in columns : 
 tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [23]:
print("step indexing, all rows with reverse rows order : \n", torch.flip(tensor, dims=(0,))) 

# negative step size doesn't work on tensor differently from numpy (Value Error)
# print("step indexing, all rows with step of 2 in columns : \n", tensor[::-1]) 

step indexing, all rows with reverse rows order : 
 tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])
