# Numpy

In [1]:
# Numpy foundamental in DL modeling in python
# Allow to create arrays and work with matrices quickly and efficently 

# Foundamental library for scientific computing in Python. 
# Provide array and matrix support to operate with this data structures

# numpy is not installed by default 
!pip install numpy 

In [2]:
import numpy as np #np is an alias for numpy to access it quickly as np

# create arrays using numpy 
## create 1D array 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
# arr1 is threated as a list apparently 
# instead it is not a list 
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
# it is a numpy array 
# I can see the shape of it 
print(arr1.shape)

(5,)


In [6]:
# To convert into rows and columns 
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5)
# it become a 2D array 
# reshaped in 1 row and 5 columns 
# I need to reshape carefully using the proper number of elements 


array([[1, 2, 3, 4, 5]])

In [ ]:
# I can create directly a row 2d vector 
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print(arr2)
print(arr2.shape)
# 2D Array (matrix)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [9]:
# To create array with in built function 
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4)) # you specify the dimension 3x4 of ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# In deep learning ones and zeros are usefull function 
# Help to initialize vector and matrices 
# Identity Matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array 
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(f'Shape: {arr.shape}, Dimension: {arr.ndim}, Size: {arr.size}, Data Type: {arr.dtype}, Item size (bytes): {arr.itemsize}')

[[1 2 3]
 [4 5 6]]
Shape: (2, 3), Dimension: 2, Size: 6, Data Type: int64, Item size (bytes): 8


In [16]:
# Numpy vectorized operations 
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element wise addition 
print("Addition")
print(arr1 + arr2)

# Elemnt wise subtraction 
print("Subtracton")
print(arr1 - arr2)

# Elemnt wise multiplication 
print("Multiplication")
print(arr1 * arr2)

# Elemnt wise division 
print("Division")
print(arr1 / arr2)


Addition
[11 22 33 44 55]
Subtracton
[ -9 -18 -27 -36 -45]
Multiplication
[ 10  40  90 160 250]
Division
[0.1 0.1 0.1 0.1 0.1]


In [17]:
# Univesal function (applyed to the whole array)
arr = np.array([2, 3, 4, 5, 6])

# square root 
print("Sqrt")
print(np.sqrt(arr))

# Exponention
print("Exp")
print(np.exp(arr))

# Sine
print("Sine")
print(np.sin(arr))

# Log
print("Log")
print(np.log(arr))

Sqrt
[1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exp
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
# Slicing operation and indexing in numpy 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
# accessing elements (similar as in list)
# you should know row and column 
arr[0][0]
arr[0,0] # same way is possible 

np.int64(1)

In [24]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
print(arr[1:]) # I access column 2 and 3

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[0:2, 1:])

[[2 3 4]
 [6 7 8]]


In [27]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [28]:
# slicing allow to access specific part of matrices
# in the same way you can modify array elements 
arr[0,0] = 100
print(arr)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [29]:
arr[1:] = 100
print(arr)
# all elements from second row 

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
# Quick statistical example 
# normalization 
# change the data to have a mean of 0 and standard deviation of 1
# formula for normalization... 
data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

# sandard normal distribution (normalization)
# this normnalization is a data conevrsion to guarantee mean 0 and std dev 1 (used in statistic)
normalized_data = (data - mean) / std_dev
print(f"Normalized data: {normalized_data}")

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
# Other statistical operators 
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print("mean ", mean)

std_dev = np.std(data)
print("std_dev ", std_dev)

variance = np.var(data)
print("variance ", variance)


mean  5.5
std_dev  2.8722813232690143
variance  8.25


In [32]:
# In pandas it is foundamental 
# Logical operations 
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
# return an array of mask with the given condition 
print(data[data > 5])

[ 6  7  8  9 10]


In [ ]:
# foundamental in data analysis to extract only some conditional elements of the list 
print(data[(data > 5) & (data<=8)])
# multiple conditions are allowed by using parentesis and conditional operators 

[6 7 8]
